# Generated by Django 6.0.3 on 2026-03-15 19:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1940), django.core.validators.MaxValueValidator(2100)])),
                ('playtime', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('genre', models.PositiveIntegerField(choices=[(1, 'Dungeon Crawler'), (2, 'Roleplaying'), (3, 'Cooperative'), (4, 'Deck Builder'), (5, 'Strategy'), (6, 'Worker Placement'), (7, 'Engine Builder'), (8, 'Legacy'), (9, 'Tile Laying'), (10, 'Social Deduction'), (11, 'Drafting'), (12, 'Party'), (13, '4X'), (14, 'Area Control'), (15, 'Puzzle'), (16, 'Miniature'), (17, 'Travel'), (18, 'Survival'), (19, 'Roll and Write'), (20, 'Adult')])),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('min_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_players', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardgame', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
