# Generated by Django 6.0.3 on 2026-03-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.PositiveIntegerField(choices=[(1, 'Dungeon Crawler'), (2, 'Roleplaying'), (3, 'Cooperative'), (4, 'Deck Builder'), (5, 'Strategy'), (6, 'Worker Placement'), (7, 'Engine Builder'), (8, 'Legacy'), (9, 'Tile Laying'), (10, 'Social Deduction'), (11, 'Drafting'), (12, 'Party'), (13, '4X'), (14, 'Area Control'), (15, 'Puzzle'), (16, 'Miniature'), (17, 'Travel'), (18, 'Survival'), (19, 'Roll and Write'), (20, 'Adult')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='rating',
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='genres',
            field=models.ManyToManyField(related_name='boardgames', to='home.genre'),
        ),
    ]
