# Generated by Django 6.0.3 on 2026-03-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20260315_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boardgames/'),
        ),
    ]
