# Generated by Django 6.0.3 on 2026-05-10 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='min_age',
            field=models.PositiveIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(100)
                ]),
        ),
    ]
