# Generated by Django 6.0.3 on 2026-05-10 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_boardgame_min_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_boardgames', to=settings.AUTH_USER_MODEL),
        ),
    ]
