# Generated by Django 6.0.3 on 2026-03-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nice_type',
            new_name='readable_type',
        ),
    ]
