# Generated by Django 6.0.3 on 2026-05-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
